name: Compile and push dist file

on:
  push:
    branches: [master]

jobs:
  compile-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Compile with ncc
        run: |
          npm install
          npx ncc build index.js -o dist
      - name: Push
        env:
          DIR: dist
        run: |
          if git diff --exit-code $DIR
          then
            exit 0
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add $DIR/*
          git commit -m "Update dist/index.js"
          git push
